# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f0c75d2d81f96c6c462c11091d1b5e5ac88c6ee0ea724acdbb3b899f748125ba6e7268058a97378dc3a2dba271fc728914f9f573644f5ffc66e078171bd1c4a4

test:
  secret_key_base: a27771028956ac8f743800593c5f1333670f951efcb113136dffd01593b2ed1573dbbaa0a9f6886511a0f1a5543481fbcf465a9200f8cb544a2dd9ff4698893c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
